Task07
Gpef/tat2016 pull request #11
Opened 2016-10-08 18:08 UTC by Gpef

2016-10-09 21:04 UTC, AlexanderSoroka requested changes

2016-10-09 21:04 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson2/task07/InputController.java
> +            if (!output.equals("")) {
Does it print somewhere that user can enter blank line to break input cycle?

2016-10-09 21:04 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson2/task07/validator/NoDigitValidator.java
> +    private String symbolsToFind = "\\D*$";
I have tested it on http://myregexp.com/ on string asdfsd3asdasd and it matches everything after 3. Are you sure it works?

2016-10-09 22:20 UTC, Gpef commented on src/com/rct/homework/lesson2/task07/validator/NoDigitValidator.java
> +    private String symbolsToFind = "\\D*$";
I think, it matches everything after '3', cause string 
"asdasd" doesn't contain any numbers. 
Input from my computer:
![image](https://cloud.githubusercontent.com/assets/1713494/19224106/b40f24ba-8e87-11e6-9bc3-0c2758e0eed7.png)

2016-10-09 22:24 UTC, Gpef commented on src/com/rct/homework/lesson2/task07/InputController.java
> +            if (!output.equals("")) {
It breaks if user input not blank line. If he inputs just blank line, it will do nothing

2016-10-10 12:21 UTC, AlexanderSoroka approved these changes

2016-10-10 12:21 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson2/task07/validator/OnlyDigitsValidator.java
> +    private String symbolsToFind = "^(\\d|\\s\\d)[\\d\\s]*$";
white space is not digit

2016-10-10 12:41 UTC, olegbaslak commented on src/com/rct/homework/lesson2/task07/validator/OnlyDigitsValidator.java
> +    private String symbolsToFind = "^(\\d|\\s\\d)[\\d\\s]*$";
but we discussed that in skype conference. 
string like " " will not' be defined as digit, but " 1" will be.

2016-10-18 21:24 UTC, merged