Dev
Gpef/tat2016 pull request #3
Opened 2016-10-02 23:37 UTC by Gpef

done lesson1.task04

2016-10-03 17:09 UTC, AlexanderSoroka requested changes
It looks quite good but there are some issues to be fixed

2016-10-03 17:09 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task04/Validator.java
> +    static double[] parse(String[] args) {
Missed comment for method parse

2016-10-03 17:09 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task04/Validator.java
> +        }catch (NumberFormatException e){
Missed spaces

2016-10-03 17:09 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task04/Validator.java
> +            e.getMessage();
Unused return value of statement e.getMessage();

2016-10-03 18:42 UTC, Gpef commented on src/com/rct/homework/lesson1/task04/Validator.java
> +            e.getMessage();
Check new commit

2016-10-03 20:13 UTC, AlexanderSoroka requested changes

2016-10-03 20:13 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task04/Main.java
> +            SquareEquation squareEquation = new SquareEquation(Validator.parse(args));
Is zero acceptable value for paramA? I don't see this check

2016-10-03 20:13 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task04/Validator.java
> +
Useless blank line

2016-10-03 20:13 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task05/Main.java
> +
Useless blank line

2016-10-03 20:13 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task05/Main.java
> +
Useless blank line

2016-10-03 20:23 UTC, Gpef commented on src/com/rct/homework/lesson1/task05/Main.java
> +
I tried to divide code to logical blocks

2016-10-03 20:40 UTC, Gpef commented on src/com/rct/homework/lesson1/task04/Main.java
> +            SquareEquation squareEquation = new SquareEquation(Validator.parse(args));
Oooops

2016-10-03 22:04 UTC, Gpef commented
Check new commits please

2016-10-04 07:02 UTC, AlexanderSoroka requested changes

2016-10-04 07:02 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task05/InputController.java
> +     * Gets {@code} paramsNumber arguments from console input.
This doesn;t say that the method ignores negatives

2016-10-04 07:02 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task05/InputController.java
> +                readString = scanner.next();
What if user inputs something very big like 2e2048?

2016-10-04 08:34 UTC, Gpef commented
Fresh updates incoming

2016-10-04 12:50 UTC, AlexanderSoroka requested changes

2016-10-04 12:50 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task04/SquareEquation.java
> +        return d;
return paramB*paramB - 4*paramA*paramC; is shorter and simpler to read, isn't it?

2016-10-04 12:50 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task04/SquareEquation.java
> +        /* eq. c = 0 */
Here and everywhere use // comments

2016-10-04 12:50 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task04/SquareEquation.java
> +        if (Validator.isZero(paramA) && !Validator.isZero(paramB)) {
This is not quadratic equation

2016-10-04 12:50 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task04/SquareEquation.java
> +        if (Validator.isZero(paramA) && !Validator.isZero(paramB)) {
I think most of these checks are useless

2016-10-04 21:08 UTC, AlexanderSoroka requested changes

2016-10-04 21:08 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task04/Validator.java
> +        } catch (NumberFormatException e) {
Is it better to expose it for caller and let it decides if application should stop or something else? Method that hides inside System.exit(1) is really bad idea - at least it must be well-documented

2016-10-04 21:08 UTC, AlexanderSoroka commented on src/com/rct/homework/lesson1/task05/Main.java
> +        try {
Let combine this 2 try catch to one

2016-10-06 06:24 UTC, AlexanderSoroka approved these changes

2016-10-08 18:03 UTC, merged